"""initial platform schema

Revision ID: 0001
Revises:
Create Date: 2026-07-16 13:59:22.736105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('last_login_at_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('android_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('last_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('approved_at_ms', sa.Integer(), nullable=True),
    sa.Column('revoked_at_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint_hash'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('android_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_android_devices_status'), ['status'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('backup_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('completed_at_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_records_created_at_ms'), ['created_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_records_status'), ['status'], unique=False)

    op.create_table('commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.Column('completed_at_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_type', 'actor_id', 'idempotency_key', name='uq_commands_actor_idempotency')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commands_created_at_ms'), ['created_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_status'), ['status'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('committed_at_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)

    op.create_table('operation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('station_id', sa.String(length=12), nullable=True),
    sa.Column('tag_id', sa.String(length=12), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('command_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=160), nullable=True),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('device_model', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_command_id'), ['command_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_created_at_ms'), ['created_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_tag_id'), ['tag_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=128), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_code'), ['product_code'], unique=True)

    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('expires_at_ms', sa.Integer(), nullable=False),
    sa.Column('last_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('revoked_at_ms', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_sessions_expires_at_ms'), ['expires_at_ms'], unique=False)

    op.create_table('device_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('install_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('poll_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('challenge_hash', sa.String(length=64), nullable=False),
    sa.Column('android_device_id', sa.String(length=36), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('expires_at_ms', sa.Integer(), nullable=False),
    sa.Column('approved_at_ms', sa.Integer(), nullable=True),
    sa.Column('token_issued_at_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['android_device_id'], ['android_devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_enrollments_android_device_id'), ['android_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_enrollments_expires_at_ms'), ['expires_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_enrollments_fingerprint_hash'), ['fingerprint_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_enrollments_status'), ['status'], unique=False)

    op.create_table('import_job_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=128), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'row_number', name='uq_import_rows_job_row')
    )
    with op.batch_alter_table('import_job_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_job_rows_job_id'), ['job_id'], unique=False)

    op.create_table('stations',
    sa.Column('station_id', sa.String(length=12), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mac', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('server_address', sa.String(length=255), nullable=True),
    sa.Column('heartbeat_seconds', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at_ms', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('station_id')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_last_heartbeat_at_ms'), ['last_heartbeat_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_status'), ['status'], unique=False)

    op.create_table('light_tags',
    sa.Column('tag_id', sa.String(length=12), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=12), nullable=True),
    sa.Column('registered_at_ms', sa.Integer(), nullable=False),
    sa.Column('first_seen_at_ms', sa.Integer(), nullable=True),
    sa.Column('last_seen_at_ms', sa.Integer(), nullable=True),
    sa.Column('battery_raw', sa.Integer(), nullable=True),
    sa.Column('battery_voltage_mv', sa.Integer(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('group_no', sa.Integer(), nullable=True),
    sa.Column('last_result_type', sa.Integer(), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('abnormal_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    with op.batch_alter_table('light_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_light_tags_battery_level'), ['battery_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_light_tags_is_abnormal'), ['is_abnormal'], unique=False)
        batch_op.create_index(batch_op.f('ix_light_tags_last_seen_at_ms'), ['last_seen_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_light_tags_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_light_tags_station_id'), ['station_id'], unique=False)

    op.create_table('bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=12), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=12), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('bound_at_ms', sa.Integer(), nullable=False),
    sa.Column('unbound_at_ms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['light_tags.tag_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_type', 'actor_id', 'idempotency_key', name='uq_bindings_actor_idempotency')
    )
    with op.batch_alter_table('bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bindings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_bindings_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bindings_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bindings_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_bindings_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bindings_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index('uq_bindings_active_tag', ['tag_id'], unique=True, sqlite_where=sa.text('is_active = 1'))

    op.create_table('command_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=12), nullable=False),
    sa.Column('tag_id', sa.String(length=12), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('first_published_at_ms', sa.Integer(), nullable=True),
    sa.Column('last_published_at_ms', sa.Integer(), nullable=True),
    sa.Column('deadline_at_ms', sa.Integer(), nullable=False),
    sa.Column('confirmed_at_ms', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tag_id'], ['light_tags.tag_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', 'tag_id', name='uq_command_items_command_tag')
    )
    with op.batch_alter_table('command_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_items_command_id'), ['command_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_items_deadline_at_ms'), ['deadline_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_items_first_published_at_ms'), ['first_published_at_ms'], unique=False)
        batch_op.create_index('ix_command_items_latest_tag', ['tag_id', 'created_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_items_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_items_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_items_tag_id'))
        batch_op.drop_index(batch_op.f('ix_command_items_status'))
        batch_op.drop_index(batch_op.f('ix_command_items_station_id'))
        batch_op.drop_index('ix_command_items_latest_tag')
        batch_op.drop_index(batch_op.f('ix_command_items_first_published_at_ms'))
        batch_op.drop_index(batch_op.f('ix_command_items_deadline_at_ms'))
        batch_op.drop_index(batch_op.f('ix_command_items_command_id'))

    op.drop_table('command_items')
    with op.batch_alter_table('bindings', schema=None) as batch_op:
        batch_op.drop_index('uq_bindings_active_tag', sqlite_where=sa.text('is_active = 1'))
        batch_op.drop_index(batch_op.f('ix_bindings_tag_id'))
        batch_op.drop_index(batch_op.f('ix_bindings_station_id'))
        batch_op.drop_index(batch_op.f('ix_bindings_source'))
        batch_op.drop_index(batch_op.f('ix_bindings_site_id'))
        batch_op.drop_index(batch_op.f('ix_bindings_product_id'))
        batch_op.drop_index(batch_op.f('ix_bindings_is_active'))

    op.drop_table('bindings')
    with op.batch_alter_table('light_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_light_tags_station_id'))
        batch_op.drop_index(batch_op.f('ix_light_tags_site_id'))
        batch_op.drop_index(batch_op.f('ix_light_tags_last_seen_at_ms'))
        batch_op.drop_index(batch_op.f('ix_light_tags_is_abnormal'))
        batch_op.drop_index(batch_op.f('ix_light_tags_battery_level'))

    op.drop_table('light_tags')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_status'))
        batch_op.drop_index(batch_op.f('ix_stations_site_id'))
        batch_op.drop_index(batch_op.f('ix_stations_last_heartbeat_at_ms'))

    op.drop_table('stations')
    with op.batch_alter_table('import_job_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_job_rows_job_id'))

    op.drop_table('import_job_rows')
    with op.batch_alter_table('device_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_device_enrollments_fingerprint_hash'))
        batch_op.drop_index(batch_op.f('ix_device_enrollments_expires_at_ms'))
        batch_op.drop_index(batch_op.f('ix_device_enrollments_android_device_id'))

    op.drop_table('device_enrollments')
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_expires_at_ms'))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_admin_user_id'))

    op.drop_table('admin_sessions')
    op.drop_table('sites')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_code'))
        batch_op.drop_index(batch_op.f('ix_products_is_active'))

    op.drop_table('products')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_tag_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_station_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_site_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_product_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_created_at_ms'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_command_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_actor_type'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_actor_id'))

    op.drop_table('operation_logs')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_status'))
        batch_op.drop_index(batch_op.f('ix_commands_created_at_ms'))

    op.drop_table('commands')
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_records_status'))
        batch_op.drop_index(batch_op.f('ix_backup_records_created_at_ms'))

    op.drop_table('backup_records')
    op.drop_table('app_settings')
    with op.batch_alter_table('android_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_android_devices_status'))

    op.drop_table('android_devices')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
